### ISSUE TITLE
Validate "or later" licenses

### ISSUE THREAD

**Issue by pombredanne** [nexB/license-expression#9]
The `master` branch implementation treats "or later" licenses as separate keys with an eventual aliases.

The `alternate-or-later-handling' branch(https://github.com/nexB/license-expression/tree/alternate-or-later-handling) implementation treats "or later" as keywords and not as separate license keys.
If this later implementation ends up a winner, if would make sense to add validation to license symbols to check if a license supports an "or later" version or not to avoid stupid things like "MIT or later"

**Comment by majurg** [comment]
#11 has been merged. Is there anything left to do here.

**Comment by RazerM** [comment]
Based on [Annex D: SPDX license expressions](https://spdx.github.io/spdx-spec/v2.3/SPDX-license-expressions/), shouldn't I be able to parse `Apache-2.0+`, for example?

https://spdx.github.io/spdx-spec/v2.3/SPDX-license-expressions/

```python
>>> from license_expression import get_spdx_licensing
>>> licensing = get_spdx_licensing()
>>> licensing.parse("Apache-2.0+", validate=True, strict=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<redacted>/python3.9/site-packages/license_expression/__init__.py", line 559, in parse
    self.validate_license_keys(expression)
  File "<redacted>/python3.9/site-packages/license_expression/__init__.py", line 466, in validate_license_keys
    raise ExpressionError(msg)
license_expression.ExpressionError: Unknown license key(s): Apache-2.0+
```

**Comment by pombredanne** [comment]
Just to explain further, here I am adding `Apache-2.0+` as an alternative SPDX id for `apache-2.0`
```Python
>>> from license_expression import *
>>> index = get_license_index()
>>> apache = [l for l in index if l["license_key"] == "apache-2.0"][0]
>>> apache["other_spdx_license_keys"].append("Apache-2.0+")
>>> spdx_licensing = build_spdx_licensing(index) 
>>> spdx_licensing.parse("Apache-2.0+", validate=True, strict=True)
LicenseSymbol('Apache-2.0', aliases=('Apache-2.0+',), is_exception=False)

```

or with a new symbol:
```Python
>>> index = get_license_index()
>>> a2plus = {'license_key': 'apache-2.0-plus', 'spdx_license_key': 'Apache-2.0+', 'other_spdx_license_keys': [], 'is_exception': False, 'is_deprecated': False, 'json': 'TBD', 'yml': 'TBD', 'html': 'TBD', 'text': 'TBD'}
>>> index.append(a2plus)
>>> spdx_licensing = build_spdx_licensing(index) 
>>> spdx_licensing.parse("Apache-2.0+", validate=True, strict=True)
LicenseSymbol('Apache-2.0+', is_exception=False)

```

**Comment by RazerM** [comment]
@pombredanne thank you for the thorough response!

I didn't see `Apache-2.0+` in the wild with my dependencies. I am evaluating the use of this library to parse licenses and I had noticed in the SPDX spec that this syntax *exists*.

Given the workarounds that are available if this does come up, it should be fine.

**Comment by pombredanne** [comment]
@RazerM you wrote:

>  I am evaluating the use of this library to parse licenses 

I can state --without a hint of bias :angel: -- that this is likely the finest license-expression parsing library available in Python (and I think I also the only one :] ) and likely one of the nicest anywhere! ... more seriously keep us posted with your eval. This is used in a few other projects such as AboutCode toolkit, ScanCode toolkit and ScanCode.io, FSFE REUSE and other places. It is supposed to be decently good at the small things it knows to do. And it is backed by a not too shabby boolean engine by @bastikr that I co-maintain. 

If there is something that does not work as it should, I would like it fixed, so your feedback is mucho welcomed!

**Comment by mgorny** [comment]
I've used license-expression as part of [pycargoebuild](https://github.com/projg2/pycargoebuild/) to parse license strings from Rust packages. Unfortunately, there are quite some people who unpredictably use `+` with licenses such as `MPL-2.0` and I'd really prefer if I hadn't to work around this, at least long term.

> You will note that even at SPDX, the use of trailing + is generally out of favor

Could you explain? I find that specification very hard to read but I couldn't find anything saying that.

**Comment by pombredanne** [comment]
@mgorny do you have a list of all these cases?
For MPL-2.0 in particular MPL-2.0+ means nothing special, the MPL-2.0 already has baked in terms that allow to use any other versions. See section 10.2:

> 10.2. Effect of New Versions
> 
> You may distribute the Covered Software under the terms of the version
> of the License under which You originally received the Covered Software,
> or under the terms of any subsequent version published by the license
> steward.

So here, we could effectively parse MPL-2.0+ to MPL-2.0 with a proper alias in the licensing symbols IMHO.

**Comment by mjherzog** [comment]
@mgorny The deprecation of "+" in favor "or-later" may not be in the spec, but it is in the (long) history of SPDX discussions. The "+" symbol was kept for backward compatibility.

**Comment by mgorny** [comment]
> @mgorny do you have a list of all these cases? For MPL-2.0 in particular MPL-2.0+ means nothing special, the MPL-2.0 already has baked in terms that allow to use any other versions. 

I don't have a list (this is the first time it was reported to me, with `MPL-2.0+`), and I know. The problem roughly is, it's valid and Rust accepts it, so people can use it, and so we have to handle it somehow. In my code I already include the automatic fallback to plain license if we don't have an explicit expansion, it's verification that's gating it. That said, I removed `verify=True` for the time being, I suppose that's good enough for us.

**Comment by mgorny** [comment]
> @mgorny The deprecation of "+" in favor "or-later" may not be in the spec, but it is in the (long) history of SPDX discussions. The "+" symbol was kept for backward compatibility.

Well, then, perhaps it should be in the spec and propagated more widely because right now new projects are using it (whether it's meaningless or not).

**Comment by pombredanne** [comment]
@mgorny 

> I don't have a list (this is the first time it was reported to me, with MPL-2.0+),

- Do you have a URL pointer to where this is seen?
- Would you have a list of published crates' license tags?

**Comment by mgorny** [comment]
> @mgorny
> 
> > I don't have a list (this is the first time it was reported to me, with MPL-2.0+),
> 
> * Do you have a URL pointer to where this is seen?

https://crates.io/crates/smartstring

> * Would you have a list of published crates' license tags?

I don't. I suppose you could grab the [database dump](https://static.crates.io/db-dump.tar.gz) (warning: 275M; linked on [data access](https://crates.io/data-access)). `data/versions.csv` has a license field, I suppose you could grab that and parse license expressions from there. Note that some old crates use `foo/bar` instead of `foo OR bar`.
